//! Phase 26.5 SC1/SC2: thin wrapper around the build.rs-generated `foxglove` module.
//!
//! `crates/roz-server/build.rs`'s second `tonic_build::configure()` call emits
//! `$OUT_DIR/foxglove.rs` containing prost Message types for every vendored
//! foxglove schema. Per research A6, `build_server(false) + build_client(false)`
//! STILL emits message types — only service/client stubs are gated. This
//! module re-exposes them at `crate::observability::foxglove_types::foxglove::*`
//! so downstream code (Plan 05 camera relay, Plan 08 SC7 test) can write
//! `foxglove::CompressedVideo { ... }.encode_to_vec()` and
//! `foxglove::CompressedVideo::decode(&bytes[..])` without hand-vendored structs.

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    unused_qualifications,
    reason = "generated prost code — upstream Foxglove proto shapes, no hand-editing"
)]
pub mod foxglove {
    tonic::include_proto!("foxglove");
}

#[cfg(test)]
mod tests {
    use super::foxglove;
    use prost::Message as _;

    #[test]
    fn compressed_video_type_exists_and_encodes() {
        let msg = foxglove::CompressedVideo {
            timestamp: Some(prost_types::Timestamp { seconds: 1, nanos: 0 }),
            frame_id: "test_cam".to_string(),
            data: vec![0x00, 0x00, 0x00, 0x01, 0x65],
            format: "h264".to_string(),
        };
        let bytes = msg.encode_to_vec();
        assert!(!bytes.is_empty(), "encoded CompressedVideo must be non-empty");
        let decoded = foxglove::CompressedVideo::decode(bytes.as_slice()).expect("round-trip decode");
        assert_eq!(decoded.format, "h264");
        assert_eq!(decoded.frame_id, "test_cam");
        assert_eq!(decoded.data, vec![0x00, 0x00, 0x00, 0x01, 0x65]);
    }

    #[test]
    fn compressed_image_type_exists() {
        // CompressedImage is vendored alongside CompressedVideo but has no
        // producer this phase (R-01). This smoke test merely proves the prost
        // type is generated by build.rs and reachable.
        let msg = foxglove::CompressedImage {
            timestamp: Some(prost_types::Timestamp { seconds: 0, nanos: 0 }),
            frame_id: "test_cam".to_string(),
            data: vec![],
            format: "jpeg".to_string(),
        };
        let bytes = msg.encode_to_vec();
        // Empty-data message still encodes (only the non-default fields are written).
        let _decoded = foxglove::CompressedImage::decode(bytes.as_slice()).expect("decode");
    }

    #[test]
    fn raw_image_type_exists() {
        // Same smoke shape for RawImage — future producer, present today.
        let _msg_type_exists = std::mem::size_of::<foxglove::RawImage>();
    }

    #[test]
    fn point_cloud_type_exists() {
        let _msg_type_exists = std::mem::size_of::<foxglove::PointCloud>();
    }

    #[test]
    fn scene_update_type_exists() {
        let _msg_type_exists = std::mem::size_of::<foxglove::SceneUpdate>();
    }

    #[test]
    fn image_annotations_type_exists() {
        let _msg_type_exists = std::mem::size_of::<foxglove::ImageAnnotations>();
    }
}
