//! Phase 26.9 Plan 07 — `/roz/camera/{name}` emit (`VideoStream` once +
//! `VideoSample` per frame). Plan 03 placed signature stubs; Plan 07
//! replaces the body.
//!
//! # Hand-vendored `CompressedVideo` proto struct
//!
//! Plan 07 RED-phase verification surfaced that Plan 01's `build.rs`
//! `compile_protos` list omits `proto/foxglove/CompressedVideo.proto`.
//! Per the plan's `<read_first>` block (which cites
//! `crates/roz-worker/src/camera/mcap_relay.rs:69-101` as a hand-vendored
//! precedent) and to keep file ownership tight to `camera.rs` in this
//! parallel-wave worktree, the `CompressedVideo` struct is hand-vendored
//! here rather than added to `build.rs`. Tags (`timestamp=1, frame_id=2,
//! data=3, format=4`) match upstream `proto/foxglove/CompressedVideo.proto`
//! verbatim.
//!
//! Followup: a future cleanup plan should add CompressedVideo.proto to
//! `crates/roz-cli/build.rs` and replace this hand-vendored struct with
//! `super::foxglove::CompressedVideo`. Field-tag drift is statically
//! impossible here (only one consumer in the crate), but a single
//! source-of-truth via tonic-build is the long-term shape.
//!
//! # Rust API shape correction vs CONTEXT D-11 / RESEARCH §Topic 3
//!
//! CONTEXT D-11 and RESEARCH §Topic 3 prescribe logging `&VideoSample`
//! directly to `rec.log(...)`. Empirically (verified 2026-04-24 against
//! `re_sdk = 0.31.3`), `rerun::components::VideoSample` does not implement
//! `AsComponents` in 0.31.3 — the per-frame logging path goes through the
//! `VideoStream` archetype's `with_sample(data)` builder method instead.
//!
//! Both first-sighting and subsequent frames therefore log a `VideoStream`,
//! but with different field sets:
//!  - First sighting per camera: `VideoStream::new(codec).with_sample(data)`
//!    — carries the codec metadata once + the first frame's sample.
//!  - Subsequent frames: `VideoStream::update_fields().with_sample(data)`
//!    — carries only the per-frame sample, leaving the static codec field
//!    untouched. This is the canonical pattern documented inline on the
//!    `VideoStream` archetype in `re_sdk_types-0.31.3`:
//!    "All components except `sample` are typically logged statically once
//!    per entity. `sample` is then logged repeatedly for each frame on the
//!    timeline."
//!
//! The dedupe semantics from CONTEXT D-11 / D-20 are preserved exactly:
//! `VideoStream`-with-codec is logged ONCE per camera entity, gated by
//! `state.seen_camera_videostream_logged.insert(camera_name)`.
#![cfg(feature = "export-rrd")]

use anyhow::{Context, Result};
use prost::Message as _;
use rerun::archetypes::VideoStream;
use rerun::components::VideoCodec;

use super::export::ConversionState;

/// Hand-vendored prost struct mirroring `foxglove.CompressedVideo`. See the
/// module-level doc comment for why this is hand-vendored rather than
/// generated by `crates/roz-cli/build.rs`. Tags match
/// `proto/foxglove/CompressedVideo.proto` exactly.
#[derive(Clone, PartialEq, ::prost::Message)]
struct CompressedVideo {
    #[prost(message, optional, tag = "1")]
    pub timestamp: Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub frame_id: String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: Vec<u8>,
    #[prost(string, tag = "4")]
    pub format: String,
}

/// Emit a `/roz/camera/{name}` (`foxglove.CompressedVideo`) frame as a
/// Rerun `VideoSample` at `/world/cameras/{name}`. The `VideoStream`
/// archetype is logged exactly once per camera entity (tracked via
/// `state.seen_camera_videostream_logged`). Plan 07 implements per
/// CONTEXT D-11/D-12.
///
/// On the FIRST frame for a given camera, logs `VideoStream` carrying
/// codec metadata (H.264) exactly once to establish the entity's stream
/// format. On EVERY frame (including the first), logs a `VideoSample`
/// component carrying the Annex B NALU bytes; keyframes (IDRs) carry
/// SPS/PPS NALUs inline per Foxglove's `CompressedVideo` contract, so
/// pass-through is byte-identical (RESEARCH §Topic 3).
///
/// # Errors
///
/// Returns an error if the MCAP payload cannot be decoded as
/// `foxglove.CompressedVideo`, or if the underlying Rerun
/// `RecordingStream::log` calls fail.
pub(super) fn emit_camera(
    rec: &rerun::RecordingStream,
    msg: &mcap::Message<'_>,
    camera_name: &str,
    state: &mut ConversionState,
) -> Result<()> {
    // Decode FIRST so a malformed payload errors before any state mutation
    // (the `malformed_payload_errors_gracefully` test asserts this ordering).
    let cv = CompressedVideo::decode(msg.data.as_ref()).context("decode foxglove.CompressedVideo")?;

    let entity_path = format!("/world/cameras/{camera_name}");

    // `cv.data` is the Annex B NALU buffer for exactly one frame.
    // Keyframes (IDRs) carry SPS/PPS NALUs inline per Foxglove's
    // `CompressedVideo` contract, so pass-through is byte-identical
    // (RESEARCH §Topic 3). Owned Vec<u8> required by `with_sample`.
    if state.seen_camera_videostream_logged.insert(camera_name.to_string()) {
        // First sighting per camera: codec metadata + first sample together
        // in one log call. The codec carries the static stream-format
        // descriptor and is logged exactly once per entity (D-11/D-20).
        rec.log(entity_path, &VideoStream::new(VideoCodec::H264).with_sample(cv.data))
            .context("rerun log VideoStream (first sighting + first sample)")?;
    } else {
        // Subsequent frames: only the per-frame sample. `update_fields`
        // returns a `VideoStream` whose codec field is left unset, so the
        // existing static codec on the entity is not re-logged.
        rec.log(entity_path, &VideoStream::update_fields().with_sample(cv.data))
            .context("rerun log VideoStream sample (subsequent frame)")?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::mcap::recording::open_rrd_writer;
    use std::borrow::Cow;
    use std::sync::Arc;

    fn synthetic_msg<'a>(topic: &'static str, data: Vec<u8>) -> mcap::Message<'a> {
        let schema = mcap::Schema {
            id: 1,
            name: "foxglove.CompressedVideo".to_string(),
            encoding: "protobuf".to_string(),
            data: Cow::Borrowed(&[]),
        };
        let channel = mcap::Channel {
            id: 1,
            topic: topic.to_string(),
            message_encoding: "protobuf".to_string(),
            schema: Some(Arc::new(schema)),
            metadata: std::collections::BTreeMap::new(),
        };
        mcap::Message {
            channel: Arc::new(channel),
            sequence: 0,
            log_time: 0,
            publish_time: 0,
            data: Cow::Owned(data),
        }
    }

    fn synthetic_compressed_video(data: Vec<u8>, camera: &str) -> Vec<u8> {
        let cv = CompressedVideo {
            timestamp: None,
            frame_id: camera.to_string(),
            data,
            format: "h264".to_string(),
        };
        cv.encode_to_vec()
    }

    fn tmp_rrd() -> (rerun::RecordingStream, tempfile::TempDir, std::path::PathBuf) {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("out.rrd");
        let rec = open_rrd_writer(&path).expect("open rrd");
        (rec, dir, path)
    }

    #[test]
    fn first_call_inserts_camera_into_state() {
        let data = synthetic_compressed_video(vec![0x00, 0x00, 0x00, 0x01, 0x65], "front");
        let msg = synthetic_msg("/roz/camera/front", data);

        let (rec, _dir, _path) = tmp_rrd();
        let mut state = ConversionState::default();
        emit_camera(&rec, &msg, "front", &mut state).expect("emit_camera ok");

        assert_eq!(state.seen_camera_videostream_logged.len(), 1);
        assert!(state.seen_camera_videostream_logged.contains("front"));
    }

    #[test]
    fn second_call_does_not_grow_state() {
        let data1 = synthetic_compressed_video(vec![0x00, 0x00, 0x00, 0x01, 0x65], "front");
        let data2 = synthetic_compressed_video(vec![0x00, 0x00, 0x00, 0x01, 0x41], "front");
        let msg1 = synthetic_msg("/roz/camera/front", data1);
        let msg2 = synthetic_msg("/roz/camera/front", data2);

        let (rec, _dir, _path) = tmp_rrd();
        let mut state = ConversionState::default();
        emit_camera(&rec, &msg1, "front", &mut state).expect("emit first ok");
        emit_camera(&rec, &msg2, "front", &mut state).expect("emit second ok");

        assert_eq!(
            state.seen_camera_videostream_logged.len(),
            1,
            "dedupe must keep the set size at 1 for a single camera"
        );
    }

    #[test]
    fn multi_camera_dedupe_tracks_each_independently() {
        let d_front = synthetic_compressed_video(vec![0x00, 0x00, 0x00, 0x01, 0x65], "front");
        let d_rear = synthetic_compressed_video(vec![0x00, 0x00, 0x00, 0x01, 0x65], "rear");
        let m_front = synthetic_msg("/roz/camera/front", d_front);
        let m_rear = synthetic_msg("/roz/camera/rear", d_rear);

        let (rec, _dir, _path) = tmp_rrd();
        let mut state = ConversionState::default();
        emit_camera(&rec, &m_front, "front", &mut state).expect("front ok");
        emit_camera(&rec, &m_rear, "rear", &mut state).expect("rear ok");

        assert_eq!(state.seen_camera_videostream_logged.len(), 2);
        assert!(state.seen_camera_videostream_logged.contains("front"));
        assert!(state.seen_camera_videostream_logged.contains("rear"));
    }

    #[test]
    fn malformed_payload_errors_gracefully() {
        // Not a valid CompressedVideo proto — first byte is a valid varint
        // start but the payload is garbage.
        let bogus = vec![0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF];
        let msg = synthetic_msg("/roz/camera/front", bogus);

        let (rec, _dir, _path) = tmp_rrd();
        let mut state = ConversionState::default();
        let err = emit_camera(&rec, &msg, "front", &mut state).expect_err("malformed payload must error");
        let s = format!("{err:#}");
        assert!(
            s.to_lowercase().contains("decode") || s.contains("CompressedVideo"),
            "expected decode error, got: {s}"
        );
        // State MUST NOT be mutated on a decode failure — the camera never
        // got its VideoStream logged.
        assert!(state.seen_camera_videostream_logged.is_empty());
    }

    #[test]
    fn produces_non_empty_rrd_with_magic() {
        let data = synthetic_compressed_video(vec![0x00, 0x00, 0x00, 0x01, 0x65], "front");
        let msg = synthetic_msg("/roz/camera/front", data);

        let (rec, _dir, path) = tmp_rrd();
        let mut state = ConversionState::default();
        emit_camera(&rec, &msg, "front", &mut state).expect("emit ok");
        drop(rec);

        let bytes = std::fs::read(&path).expect("read rrd");
        assert!(bytes.len() > 4);
        assert_eq!(&bytes[..4], b"RRF2");
    }
}
