//! gRPC IO backends for the controller loop.
//!
//! [`GrpcSensorSource`] connects to the `substrate-sim-bridge` gRPC service
//! and streams pose data into [`SensorFrame`]s.  [`GrpcActuatorSink`] is a
//! stub that will forward joint commands once the bridge exposes a
//! `SendJointCommand` RPC.

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use tokio_stream::StreamExt;

use roz_core::channels::InterfaceType;
use roz_core::command::CommandFrame;
use roz_core::spatial::EntityState;

use crate::io::{ActuatorSink, SensorFrame, SensorSource};

// ---------------------------------------------------------------------------
// Proto stubs (generated by tonic-build in build.rs)
// ---------------------------------------------------------------------------

#[allow(
    dead_code,
    clippy::doc_markdown,
    clippy::derive_partial_eq_without_eq,
    clippy::default_trait_access,
    clippy::large_enum_variant,
    clippy::struct_excessive_bools,
    clippy::missing_const_for_fn,
    clippy::trivially_copy_pass_by_ref
)]
pub mod proto {
    tonic::include_proto!("substrate.sim");
}

use proto::control_service_client::ControlServiceClient;
use proto::scene_service_client::SceneServiceClient;

// ---------------------------------------------------------------------------
// GrpcSensorSource
// ---------------------------------------------------------------------------

/// Streams [`PoseBatch`] from the substrate-sim-bridge and buffers the latest
/// [`SensorFrame`] for the controller loop to consume each tick.
///
/// A background tokio task maintains a persistent gRPC stream.  The controller
/// calls [`try_recv`] at 100 Hz; it returns `Some` when new data has arrived
/// since the last call, `None` otherwise.
///
/// [`try_recv`]: SensorSource::try_recv
pub struct GrpcSensorSource {
    latest: Arc<parking_lot::Mutex<Option<SensorFrame>>>,
    _handle: tokio::task::JoinHandle<()>,
}

impl GrpcSensorSource {
    /// Connect to the bridge at `bridge_url` and begin streaming poses.
    ///
    /// # Errors
    ///
    /// Returns an error if the initial gRPC connection fails.
    pub async fn connect(bridge_url: &str) -> anyhow::Result<Self> {
        let channel = tonic::transport::Channel::from_shared(bridge_url.to_string())?
            .connect()
            .await?;

        let latest: Arc<parking_lot::Mutex<Option<SensorFrame>>> = Arc::new(parking_lot::Mutex::new(None));
        let latest_writer = Arc::clone(&latest);

        let handle = tokio::spawn(async move {
            Self::stream_loop(channel, latest_writer).await;
        });

        Ok(Self {
            latest,
            _handle: handle,
        })
    }

    /// Background loop: opens a `StreamPoses` stream and buffers each batch.
    ///
    /// If the stream breaks, logs a warning and exits.  A production version
    /// would reconnect with exponential backoff.
    async fn stream_loop(channel: tonic::transport::Channel, latest: Arc<parking_lot::Mutex<Option<SensorFrame>>>) {
        let mut client = SceneServiceClient::new(channel);

        let request = proto::StreamPosesRequest {
            world_name: String::new(),
            entity_filter: vec![],
        };

        let stream = match client.stream_poses(request).await {
            Ok(response) => response.into_inner(),
            Err(e) => {
                tracing::error!(error = %e, "StreamPoses RPC failed");
                return;
            }
        };

        tokio::pin!(stream);

        while let Some(result) = stream.next().await {
            match result {
                Ok(batch) => {
                    let frame = pose_batch_to_sensor_frame(&batch);
                    *latest.lock() = Some(frame);
                }
                Err(e) => {
                    tracing::warn!(error = %e, "StreamPoses stream error, exiting");
                    return;
                }
            }
        }

        tracing::info!("StreamPoses stream ended");
    }
}

impl SensorSource for GrpcSensorSource {
    fn try_recv(&mut self) -> Option<SensorFrame> {
        self.latest.lock().take()
    }
}

// ---------------------------------------------------------------------------
// GrpcActuatorSink
// ---------------------------------------------------------------------------

/// Sends joint velocity commands to the bridge via `SendJointCommand` RPC.
///
/// Uses a persistent gRPC channel (created once, reused across ticks).
/// Each [`send`] spawns a fire-and-forget async task.  If a background
/// send fails, the error surfaces on the next synchronous [`send`] call
/// via the `last_error` [`AtomicBool`].
///
/// [`send`]: ActuatorSink::send
pub struct GrpcActuatorSink {
    /// Persistent gRPC client (cloneable, cheap — reuses the underlying channel).
    client: ControlServiceClient<tonic::transport::Channel>,
    /// Channel names in manifest order.
    channel_names: Vec<String>,
    /// Robot class for bridge routing ("manipulator", "drone", "mobile").
    robot_class: String,
    /// Proto-encoded [`proto::JointCommandMode`] derived from the manifest's
    /// [`InterfaceType`](roz_core::channels::InterfaceType).
    command_mode: i32,
    /// Tokio runtime handle for spawning fire-and-forget sends.
    runtime: tokio::runtime::Handle,
    /// Set by a background send task on failure; cleared on the next [`send`].
    last_error: Arc<AtomicBool>,
}

impl GrpcActuatorSink {
    /// Create a new actuator sink from a channel manifest.
    ///
    /// `channel` should point to the substrate-sim-bridge gRPC endpoint.
    /// Channel names and robot class are extracted from the manifest.
    #[must_use]
    pub fn from_manifest(
        channel: tonic::transport::Channel,
        manifest: &roz_core::channels::ChannelManifest,
        runtime: tokio::runtime::Handle,
    ) -> Self {
        debug_assert!(
            manifest
                .commands
                .windows(2)
                .all(|w| w[0].interface_type == w[1].interface_type),
            "GrpcActuatorSink assumes uniform InterfaceType across all command channels"
        );

        let command_mode = manifest
            .commands
            .first()
            .map_or(proto::JointCommandMode::JointVelocity as i32, |c| {
                match c.interface_type {
                    InterfaceType::Position => proto::JointCommandMode::JointPosition.into(),
                    InterfaceType::Velocity => proto::JointCommandMode::JointVelocity.into(),
                    InterfaceType::Effort => {
                        tracing::warn!(
                            "Effort InterfaceType not natively supported by bridge; falling back to JointVelocity mode"
                        );
                        proto::JointCommandMode::JointVelocity.into()
                    }
                }
            });

        Self {
            client: ControlServiceClient::new(channel),
            channel_names: manifest.commands.iter().map(|c| c.name.clone()).collect(),
            robot_class: manifest.robot_class.clone(),
            command_mode,
            runtime,
            last_error: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Create a new actuator sink with explicit names (backward compat).
    ///
    /// Defaults to `JointVelocity` mode for backward compatibility.
    #[must_use]
    pub fn new(channel: tonic::transport::Channel, joint_names: Vec<String>, runtime: tokio::runtime::Handle) -> Self {
        Self {
            client: ControlServiceClient::new(channel),
            channel_names: joint_names,
            robot_class: "manipulator".into(),
            command_mode: proto::JointCommandMode::JointVelocity.into(),
            runtime,
            last_error: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Returns `true` if a previous background send encountered an error.
    #[must_use]
    pub fn had_error(&self) -> bool {
        self.last_error.load(Ordering::Relaxed)
    }
}

impl ActuatorSink for GrpcActuatorSink {
    fn send(&self, frame: &CommandFrame) -> anyhow::Result<()> {
        // Log (don't bail) previous async errors — bailing would throttle 100Hz sends.
        if self.last_error.swap(false, Ordering::Relaxed) {
            tracing::warn!("previous gRPC send failed (see logs for details)");
        }

        let mut client = self.client.clone(); // tonic client clone is cheap (Arc-based)
        let names = self.channel_names.clone();
        let values = frame.values.clone();
        let robot_class = self.robot_class.clone();
        let command_mode = self.command_mode;
        let error_flag = Arc::clone(&self.last_error);

        self.runtime.spawn(async move {
            let request = proto::JointCommandRequest {
                mode: command_mode,
                joint_names: names,
                values,
                world_name: String::new(),
                robot_class,
            };

            match client.send_joint_command(request).await {
                Ok(response) => {
                    let inner = response.into_inner();
                    if !inner.success {
                        tracing::warn!(error = inner.error, "SendJointCommand returned error");
                        error_flag.store(true, Ordering::Relaxed);
                    }
                }
                Err(e) => {
                    tracing::warn!(error = %e, "SendJointCommand RPC failed");
                    error_flag.store(true, Ordering::Relaxed);
                }
            }
        });

        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

/// Convert a gRPC [`PoseBatch`] into a [`SensorFrame`].
fn pose_batch_to_sensor_frame(batch: &proto::PoseBatch) -> SensorFrame {
    let entities: Vec<EntityState> = batch.poses.iter().map(entity_pose_to_state).collect();

    #[expect(
        clippy::cast_possible_truncation,
        reason = "sim_time seconds to nanos; truncation is acceptable for simulation timestamps"
    )]
    let sim_time_ns = (batch.sim_time * 1_000_000_000.0) as i64;

    SensorFrame {
        entities,
        joint_positions: Vec::new(),
        joint_velocities: Vec::new(),
        sim_time_ns,
    }
}

/// Convert a single gRPC [`EntityPose`] into an [`EntityState`].
fn entity_pose_to_state(ep: &proto::EntityPose) -> EntityState {
    let (position, orientation) = ep.transform.as_ref().map_or((None, None), |t| {
        (
            Some([t.x, t.y, t.z]),
            Some([t.qw, t.qx, t.qy, t.qz]), // roz convention: [w, x, y, z]
        )
    });

    EntityState {
        id: ep.path.clone(),
        kind: "gazebo_model".to_owned(),
        position,
        orientation,
        velocity: None,
        properties: HashMap::new(),
        timestamp_ns: None,
        frame_id: Some("world".to_owned()),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use super::*;

    #[test]
    fn pose_batch_converts_to_sensor_frame() {
        let batch = proto::PoseBatch {
            poses: vec![
                proto::EntityPose {
                    entity_id: 1,
                    path: "world/robot/base_link".to_owned(),
                    transform: Some(proto::Transform3D {
                        x: 1.0,
                        y: 2.0,
                        z: 3.0,
                        qx: 0.0,
                        qy: 0.0,
                        qz: 0.0,
                        qw: 1.0,
                        sx: 1.0,
                        sy: 1.0,
                        sz: 1.0,
                    }),
                },
                proto::EntityPose {
                    entity_id: 2,
                    path: "world/camera".to_owned(),
                    transform: None,
                },
            ],
            sim_time: 1.5,
        };

        let frame = pose_batch_to_sensor_frame(&batch);

        assert_eq!(frame.entities.len(), 2);
        assert_eq!(frame.sim_time_ns, 1_500_000_000);

        let robot = &frame.entities[0];
        assert_eq!(robot.id, "world/robot/base_link");
        assert_eq!(robot.kind, "gazebo_model");
        assert_eq!(robot.position, Some([1.0, 2.0, 3.0]));
        assert_eq!(robot.orientation, Some([1.0, 0.0, 0.0, 0.0])); // [w,x,y,z]
        assert_eq!(robot.frame_id.as_deref(), Some("world"));

        let camera = &frame.entities[1];
        assert_eq!(camera.id, "world/camera");
        assert!(camera.position.is_none());
        assert!(camera.orientation.is_none());
    }

    #[tokio::test]
    async fn grpc_actuator_sink_stub_logs() {
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();
        let sink = GrpcActuatorSink::new(channel, vec!["j1".into()], tokio::runtime::Handle::current());
        let frame = CommandFrame::zero(1);
        assert!(sink.send(&frame).is_ok());
        assert!(!sink.had_error());
    }

    #[tokio::test]
    async fn grpc_actuator_sink_clears_last_error_without_bailing() {
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();
        let sink = GrpcActuatorSink::new(channel, vec!["j1".into()], tokio::runtime::Handle::current());

        // Simulate a background error.
        sink.last_error.store(true, Ordering::Relaxed);

        // send() should warn but NOT bail — keeps 100Hz throughput.
        let result = sink.send(&CommandFrame::zero(1));
        assert!(result.is_ok(), "send should not bail on previous error");

        // Error flag should be cleared after surfacing.
        assert!(!sink.had_error());
    }

    #[tokio::test]
    #[ignore]
    async fn grpc_sensor_source_receives_poses() {
        let mut source = GrpcSensorSource::connect("http://127.0.0.1:9090").await.unwrap();

        // Give the background stream time to receive at least one batch.
        tokio::time::sleep(Duration::from_secs(1)).await;

        let frame = source.try_recv();
        assert!(frame.is_some(), "should receive sensor data from bridge");
        let frame = frame.unwrap();
        assert!(!frame.entities.is_empty(), "should have entities");
        println!("Received {} entities", frame.entities.len());
    }
}
