//! gRPC IO backends for the controller loop.
//!
//! [`GrpcSensorSource`] connects to the `substrate-sim-bridge` gRPC service
//! and streams pose data into [`SensorFrame`]s.  [`GrpcActuatorSink`] is a
//! stub that will forward joint commands once the bridge exposes a
//! `SendJointCommand` RPC.

#![allow(clippy::missing_const_for_fn)]

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use tokio_stream::StreamExt;

use roz_core::command::CommandFrame;
use roz_core::embodiment::binding::{BindingType, CommandInterfaceType, ControlInterfaceManifest};
use roz_core::embodiment::{FrameSnapshotInput, FrameSource, TimestampedTransform, Transform3D};
use roz_core::session::snapshot::FreshnessState;
use roz_core::spatial::EntityState;

use crate::io::{ActuatorSink, SensorFrame, SensorSource};

// ---------------------------------------------------------------------------
// Proto stubs (generated by tonic-build in build.rs)
// ---------------------------------------------------------------------------

#[allow(
    dead_code,
    clippy::doc_markdown,
    clippy::derive_partial_eq_without_eq,
    clippy::default_trait_access,
    clippy::large_enum_variant,
    clippy::struct_excessive_bools,
    clippy::missing_const_for_fn,
    clippy::trivially_copy_pass_by_ref,
    // Generated proto code — allow all pedantic/nursery/style that tonic-build
    // may emit. Additional lints seen in CI: or_fun_call, type_complexity.
    clippy::pedantic,
    clippy::nursery,
    clippy::or_fun_call,
    clippy::type_complexity
)]
pub mod proto {
    tonic::include_proto!("substrate.sim");
}

use proto::control_service_client::ControlServiceClient;
use proto::scene_service_client::SceneServiceClient;

// ---------------------------------------------------------------------------
// GrpcSensorSource
// ---------------------------------------------------------------------------

/// Streams [`PoseBatch`] from the substrate-sim-bridge and buffers the latest
/// [`SensorFrame`] for the controller loop to consume each tick.
///
/// A background tokio task maintains a persistent gRPC stream.  The controller
/// calls [`try_recv`] at 100 Hz; it returns `Some` when new data has arrived
/// since the last call, `None` otherwise.
///
/// [`try_recv`]: SensorSource::try_recv
pub struct GrpcSensorSource {
    latest: Arc<parking_lot::Mutex<Option<SensorFrame>>>,
    _handle: tokio::task::JoinHandle<()>,
}

impl GrpcSensorSource {
    /// Connect to the bridge at `bridge_url` and begin streaming poses.
    ///
    /// # Errors
    ///
    /// Returns an error if the initial gRPC connection fails.
    pub async fn connect(bridge_url: &str) -> anyhow::Result<Self> {
        let channel = tonic::transport::Channel::from_shared(bridge_url.to_string())?
            .connect()
            .await?;

        let latest: Arc<parking_lot::Mutex<Option<SensorFrame>>> = Arc::new(parking_lot::Mutex::new(None));
        let latest_writer = Arc::clone(&latest);

        let handle = tokio::spawn(async move {
            Self::stream_loop(channel, latest_writer).await;
        });

        Ok(Self {
            latest,
            _handle: handle,
        })
    }

    /// Background loop: opens a `StreamPoses` stream and buffers each batch.
    ///
    /// If the stream breaks, logs a warning and exits.  A production version
    /// would reconnect with exponential backoff.
    async fn stream_loop(channel: tonic::transport::Channel, latest: Arc<parking_lot::Mutex<Option<SensorFrame>>>) {
        let mut client = SceneServiceClient::new(channel);

        let request = proto::StreamPosesRequest {
            world_name: String::new(),
            entity_filter: vec![],
        };

        let stream = match client.stream_poses(request).await {
            Ok(response) => response.into_inner(),
            Err(e) => {
                tracing::error!(error = %e, "StreamPoses RPC failed");
                return;
            }
        };

        tokio::pin!(stream);

        while let Some(result) = stream.next().await {
            match result {
                Ok(batch) => {
                    let frame = pose_batch_to_sensor_frame(&batch);
                    *latest.lock() = Some(frame);
                }
                Err(e) => {
                    tracing::warn!(error = %e, "StreamPoses stream error, exiting");
                    return;
                }
            }
        }

        tracing::info!("StreamPoses stream ended");
    }
}

impl SensorSource for GrpcSensorSource {
    fn try_recv(&mut self) -> Option<SensorFrame> {
        self.latest.lock().take()
    }
}

// ---------------------------------------------------------------------------
// GrpcActuatorSink
// ---------------------------------------------------------------------------

/// Sends joint velocity commands to the bridge via `SendJointCommand` RPC.
///
/// Uses a persistent gRPC channel (created once, reused across ticks).
/// Each [`send`] spawns a fire-and-forget async task.  If a background
/// send fails, the error surfaces on the next synchronous [`send`] call
/// via the `last_error` [`AtomicBool`].
///
/// [`send`]: ActuatorSink::send
pub struct GrpcActuatorSink {
    /// Persistent gRPC client (cloneable, cheap — reuses the underlying channel).
    client: ControlServiceClient<tonic::transport::Channel>,
    /// Channel names in manifest order.
    channel_names: Vec<String>,
    /// Robot class for bridge routing ("manipulator", "drone", "mobile").
    robot_class: String,
    /// Proto-encoded [`proto::JointCommandMode`] derived from the manifest's
    /// [`InterfaceType`](roz_core::channels::InterfaceType).
    command_mode: i32,
    /// Stable owner identity for this sink's low-level control lease.
    owner_id: String,
    /// Serialized low-level control lease state shared with background sends.
    lease_state: Arc<parking_lot::Mutex<LeaseState>>,
    /// Tokio runtime handle for spawning fire-and-forget sends.
    runtime: tokio::runtime::Handle,
    /// Set by a background send task on failure; cleared on the next [`send`].
    last_error: Arc<AtomicBool>,
    /// Most recent background send error, if any.
    last_error_message: Arc<parking_lot::Mutex<Option<String>>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum LeaseState {
    Idle,
    Acquiring,
    Owned,
    DropRequested,
}

impl GrpcActuatorSink {
    fn new_owner_id() -> String {
        format!("copper-{}", uuid::Uuid::new_v4())
    }

    const fn is_actuator_channel(interface_type: &CommandInterfaceType) -> bool {
        matches!(
            interface_type,
            CommandInterfaceType::JointPosition
                | CommandInterfaceType::JointVelocity
                | CommandInterfaceType::JointTorque
                | CommandInterfaceType::GripperPosition
                | CommandInterfaceType::GripperForce
        )
    }

    const fn command_mode_for_interface(interface_type: &CommandInterfaceType) -> Option<i32> {
        match interface_type {
            CommandInterfaceType::JointPosition | CommandInterfaceType::GripperPosition => {
                Some(proto::JointCommandMode::JointPosition as i32)
            }
            CommandInterfaceType::JointVelocity => Some(proto::JointCommandMode::JointVelocity as i32),
            CommandInterfaceType::JointTorque
            | CommandInterfaceType::GripperForce
            | CommandInterfaceType::ForceTorqueSensor
            | CommandInterfaceType::ImuSensor => None,
        }
    }

    const fn is_actuator_binding(binding_type: &BindingType) -> bool {
        matches!(
            binding_type,
            BindingType::JointPosition
                | BindingType::JointVelocity
                | BindingType::Command
                | BindingType::GripperPosition
                | BindingType::GripperForce
        )
    }

    fn normalize_bridge_joint_name(robot_class: &str, name: &str) -> String {
        if robot_class != "manipulator" {
            return name.to_string();
        }

        let Some((prefix, leaf)) = name.rsplit_once('/') else {
            return if name.ends_with("_joint") {
                name.to_string()
            } else {
                format!("{name}_joint")
            };
        };

        if leaf.ends_with("_joint") {
            name.to_string()
        } else {
            format!("{prefix}/{leaf}_joint")
        }
    }

    fn actuator_names_from_control_manifest(
        control_manifest: &ControlInterfaceManifest,
        robot_class: &str,
    ) -> Vec<String> {
        control_manifest
            .channels
            .iter()
            .enumerate()
            .filter(|(_, channel)| Self::is_actuator_channel(&channel.interface_type))
            .map(|(index, channel)| {
                let bound_name = control_manifest
                    .bindings
                    .iter()
                    .find(|binding| {
                        usize::try_from(binding.channel_index).ok() == Some(index)
                            && Self::is_actuator_binding(&binding.binding_type)
                    })
                    .map_or(channel.name.as_str(), |binding| binding.physical_name.as_str());
                Self::normalize_bridge_joint_name(robot_class, bound_name)
            })
            .collect()
    }

    fn validate_actuator_layout(
        control_manifest: &ControlInterfaceManifest,
        robot_class: &str,
    ) -> anyhow::Result<(Vec<String>, i32)> {
        let actuator_channels: Vec<&roz_core::embodiment::binding::ControlChannelDef> = control_manifest
            .channels
            .iter()
            .filter(|channel| Self::is_actuator_channel(&channel.interface_type))
            .collect();
        let first = actuator_channels
            .first()
            .ok_or_else(|| anyhow::anyhow!("control manifest has no actuator channels for gRPC output"))?;
        let command_mode = Self::command_mode_for_interface(&first.interface_type).ok_or_else(|| {
            anyhow::anyhow!(
                "gRPC actuator sink does not support {:?} command channels",
                first.interface_type
            )
        })?;
        for channel in actuator_channels.iter().skip(1) {
            let mode = Self::command_mode_for_interface(&channel.interface_type).ok_or_else(|| {
                anyhow::anyhow!(
                    "gRPC actuator sink does not support {:?} command channels",
                    channel.interface_type
                )
            })?;
            if mode != command_mode {
                anyhow::bail!(
                    "gRPC actuator sink requires homogeneous actuator interfaces, found {:?} and {:?}",
                    first.interface_type,
                    channel.interface_type
                );
            }
        }
        Ok((
            Self::actuator_names_from_control_manifest(control_manifest, robot_class),
            command_mode,
        ))
    }

    async fn release_low_level_control_best_effort(
        client: &mut ControlServiceClient<tonic::transport::Channel>,
        robot_class: &str,
        owner_id: &str,
    ) {
        if let Err(error) = client
            .release_low_level_control(proto::ReleaseLowLevelControlRequest {
                robot_class: robot_class.to_string(),
                owner_id: owner_id.to_string(),
            })
            .await
        {
            tracing::warn!(error = %error, "ReleaseLowLevelControl RPC failed");
        }
    }

    /// Create a new actuator sink from the canonical control interface manifest.
    ///
    /// `robot_class` remains explicit because it is not encoded by
    /// [`ControlInterfaceManifest`].
    pub fn from_control_manifest(
        channel: tonic::transport::Channel,
        control_manifest: &ControlInterfaceManifest,
        robot_class: impl Into<String>,
        runtime: tokio::runtime::Handle,
    ) -> anyhow::Result<Self> {
        let robot_class = robot_class.into();
        let (channel_names, command_mode) = Self::validate_actuator_layout(control_manifest, &robot_class)?;
        Ok(Self {
            client: ControlServiceClient::new(channel),
            channel_names,
            robot_class,
            command_mode,
            owner_id: Self::new_owner_id(),
            lease_state: Arc::new(parking_lot::Mutex::new(LeaseState::Idle)),
            runtime,
            last_error: Arc::new(AtomicBool::new(false)),
            last_error_message: Arc::new(parking_lot::Mutex::new(None)),
        })
    }

    /// Create a new actuator sink with explicit names (backward compat).
    ///
    /// Defaults to `JointVelocity` mode for backward compatibility.
    #[must_use]
    pub fn new(channel: tonic::transport::Channel, joint_names: Vec<String>, runtime: tokio::runtime::Handle) -> Self {
        Self {
            client: ControlServiceClient::new(channel),
            channel_names: joint_names,
            robot_class: "manipulator".into(),
            command_mode: proto::JointCommandMode::JointVelocity.into(),
            owner_id: Self::new_owner_id(),
            lease_state: Arc::new(parking_lot::Mutex::new(LeaseState::Idle)),
            runtime,
            last_error: Arc::new(AtomicBool::new(false)),
            last_error_message: Arc::new(parking_lot::Mutex::new(None)),
        }
    }

    /// Returns `true` if a previous background send encountered an error.
    #[must_use]
    pub fn had_error(&self) -> bool {
        self.last_error.load(Ordering::Relaxed)
    }

    /// Returns the most recent background send error, if any.
    #[must_use]
    pub fn last_error_message(&self) -> Option<String> {
        self.last_error_message.lock().clone()
    }
}

impl ActuatorSink for GrpcActuatorSink {
    #[allow(clippy::too_many_lines)]
    fn send(&self, frame: &CommandFrame) -> anyhow::Result<()> {
        // Log (don't bail) previous async errors — bailing would throttle 100Hz sends.
        if self.last_error.swap(false, Ordering::Relaxed) {
            tracing::warn!("previous gRPC send failed (see logs for details)");
        }
        if frame.values.len() != self.channel_names.len() {
            anyhow::bail!(
                "command frame width mismatch: expected {} values for {:?}, got {}",
                self.channel_names.len(),
                self.channel_names,
                frame.values.len()
            );
        }

        let mut client = self.client.clone(); // tonic client clone is cheap (Arc-based)
        let names = self.channel_names.clone();
        let values = frame.values.clone();
        let robot_class = self.robot_class.clone();
        let command_mode = self.command_mode;
        let owner_id = self.owner_id.clone();
        let lease_state = Arc::clone(&self.lease_state);
        let error_flag = Arc::clone(&self.last_error);
        let error_message = Arc::clone(&self.last_error_message);
        let should_acquire = {
            let mut state = lease_state.lock();
            let should_acquire = match *state {
                LeaseState::Idle => {
                    *state = LeaseState::Acquiring;
                    true
                }
                LeaseState::Acquiring | LeaseState::Owned => false,
                LeaseState::DropRequested => {
                    anyhow::bail!("gRPC actuator sink is shutting down");
                }
            };
            drop(state);
            should_acquire
        };

        self.runtime.spawn(async move {
            if should_acquire {
                match client
                    .acquire_low_level_control(proto::AcquireLowLevelControlRequest {
                        robot_class: robot_class.clone(),
                        owner_id: owner_id.clone(),
                        requested_mode: command_mode,
                    })
                    .await
                {
                    Ok(response) => {
                        let inner = response.into_inner();
                        if !inner.success {
                            tracing::warn!(error = inner.error, "AcquireLowLevelControl returned error");
                            error_flag.store(true, Ordering::Relaxed);
                            *error_message.lock() = Some(inner.error);
                            *lease_state.lock() = LeaseState::Idle;
                            return;
                        }
                        let should_release = {
                            let mut state = lease_state.lock();
                            if *state == LeaseState::DropRequested {
                                *state = LeaseState::Idle;
                                true
                            } else {
                                *state = LeaseState::Owned;
                                false
                            }
                        };
                        if should_release {
                            Self::release_low_level_control_best_effort(&mut client, &robot_class, &owner_id).await;
                            return;
                        }
                    }
                    Err(e) => {
                        tracing::warn!(error = %e, "AcquireLowLevelControl RPC failed");
                        error_flag.store(true, Ordering::Relaxed);
                        *error_message.lock() = Some(e.to_string());
                        *lease_state.lock() = LeaseState::Idle;
                        return;
                    }
                }
            }

            let request = proto::JointCommandRequest {
                mode: command_mode,
                joint_names: names,
                values,
                world_name: String::new(),
                robot_class: robot_class.clone(),
                owner_id: owner_id.clone(),
                acquire_low_level_if_needed: true,
            };

            match client.send_joint_command(request).await {
                Ok(response) => {
                    let inner = response.into_inner();
                    if inner.success {
                        let should_release = {
                            let mut state = lease_state.lock();
                            if *state == LeaseState::DropRequested {
                                *state = LeaseState::Idle;
                                true
                            } else {
                                *state = LeaseState::Owned;
                                false
                            }
                        };
                        if should_release {
                            Self::release_low_level_control_best_effort(&mut client, &robot_class, &owner_id).await;
                        }
                        *error_message.lock() = None;
                    } else {
                        tracing::warn!(error = inner.error, "SendJointCommand returned error");
                        error_flag.store(true, Ordering::Relaxed);
                        *error_message.lock() = Some(inner.error);
                        *lease_state.lock() = LeaseState::Idle;
                        Self::release_low_level_control_best_effort(&mut client, &robot_class, &owner_id).await;
                    }
                }
                Err(e) => {
                    tracing::warn!(error = %e, "SendJointCommand RPC failed");
                    error_flag.store(true, Ordering::Relaxed);
                    *error_message.lock() = Some(e.to_string());
                    *lease_state.lock() = LeaseState::Idle;
                    Self::release_low_level_control_best_effort(&mut client, &robot_class, &owner_id).await;
                }
            }
        });

        Ok(())
    }
}

impl Drop for GrpcActuatorSink {
    fn drop(&mut self) {
        {
            let mut state = self.lease_state.lock();
            match *state {
                LeaseState::Idle | LeaseState::DropRequested => return,
                LeaseState::Acquiring => {
                    *state = LeaseState::DropRequested;
                    return;
                }
                LeaseState::Owned => {
                    *state = LeaseState::DropRequested;
                }
            }
        }
        let mut client = self.client.clone();
        let robot_class = self.robot_class.clone();
        let owner_id = self.owner_id.clone();
        self.runtime.spawn(async move {
            Self::release_low_level_control_best_effort(&mut client, &robot_class, &owner_id).await;
        });
    }
}

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

/// Convert a gRPC [`PoseBatch`] into a [`SensorFrame`].
fn pose_batch_to_sensor_frame(batch: &proto::PoseBatch) -> SensorFrame {
    let entities: Vec<EntityState> = batch.poses.iter().map(entity_pose_to_state).collect();

    #[expect(
        clippy::cast_possible_truncation,
        reason = "sim_time seconds to nanos; truncation is acceptable for simulation timestamps"
    )]
    let sim_time_ns = (batch.sim_time * 1_000_000_000.0) as i64;

    SensorFrame {
        entities,
        joint_positions: Vec::new(),
        joint_velocities: Vec::new(),
        sim_time_ns,
        wrench: None,
        contact: None,
        frame_snapshot_input: pose_batch_to_snapshot_input(batch, sim_time_ns),
    }
}

fn pose_batch_to_snapshot_input(batch: &proto::PoseBatch, sim_time_ns: i64) -> FrameSnapshotInput {
    let timestamp_ns = u64::try_from(sim_time_ns).unwrap_or(0);
    let dynamic_transforms = batch
        .poses
        .iter()
        .filter_map(|pose| {
            let transform = pose.transform.as_ref()?;
            let frame_id = canonical_frame_id_from_pose_path(&pose.path);
            if frame_id.is_empty() {
                return None;
            }
            Some(TimestampedTransform {
                frame_id,
                parent_id: Some("world".into()),
                transform: Transform3D {
                    translation: [transform.x, transform.y, transform.z],
                    rotation: [transform.qw, transform.qx, transform.qy, transform.qz],
                    timestamp_ns,
                },
                freshness: FreshnessState::Fresh,
                source: FrameSource::Dynamic,
            })
        })
        .collect();

    FrameSnapshotInput {
        dynamic_transforms,
        ..FrameSnapshotInput::default()
    }
}

fn canonical_frame_id_from_pose_path(path: &str) -> String {
    path.rsplit('/')
        .find(|segment| !segment.is_empty())
        .unwrap_or(path)
        .to_string()
}

/// Convert a single gRPC [`EntityPose`] into an [`EntityState`].
fn entity_pose_to_state(ep: &proto::EntityPose) -> EntityState {
    let (position, orientation) = ep.transform.as_ref().map_or((None, None), |t| {
        (
            Some([t.x, t.y, t.z]),
            Some([t.qw, t.qx, t.qy, t.qz]), // roz convention: [w, x, y, z]
        )
    });

    EntityState {
        id: ep.path.clone(),
        kind: "gazebo_model".to_owned(),
        position,
        orientation,
        velocity: None,
        properties: HashMap::new(),
        timestamp_ns: None,
        frame_id: "world".to_owned(),
        last_observed_ns: None,
        observation_confidence: 0.0,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use super::*;

    #[test]
    fn pose_batch_converts_to_sensor_frame() {
        let batch = proto::PoseBatch {
            poses: vec![
                proto::EntityPose {
                    entity_id: 1,
                    path: "world/robot/base_link".to_owned(),
                    transform: Some(proto::Transform3D {
                        x: 1.0,
                        y: 2.0,
                        z: 3.0,
                        qx: 0.0,
                        qy: 0.0,
                        qz: 0.0,
                        qw: 1.0,
                        sx: 1.0,
                        sy: 1.0,
                        sz: 1.0,
                    }),
                },
                proto::EntityPose {
                    entity_id: 2,
                    path: "world/camera".to_owned(),
                    transform: None,
                },
            ],
            sim_time: 1.5,
        };

        let frame = pose_batch_to_sensor_frame(&batch);

        assert_eq!(frame.entities.len(), 2);
        assert_eq!(frame.sim_time_ns, 1_500_000_000);
        assert_eq!(frame.frame_snapshot_input.dynamic_transforms.len(), 1);
        assert_eq!(frame.frame_snapshot_input.dynamic_transforms[0].frame_id, "base_link");
        assert_eq!(
            frame.frame_snapshot_input.dynamic_transforms[0].transform.translation,
            [1.0, 2.0, 3.0]
        );

        let robot = &frame.entities[0];
        assert_eq!(robot.id, "world/robot/base_link");
        assert_eq!(robot.kind, "gazebo_model");
        assert_eq!(robot.position, Some([1.0, 2.0, 3.0]));
        assert_eq!(robot.orientation, Some([1.0, 0.0, 0.0, 0.0])); // [w,x,y,z]
        assert_eq!(robot.frame_id, "world");

        let camera = &frame.entities[1];
        assert_eq!(camera.id, "world/camera");
        assert!(camera.position.is_none());
        assert!(camera.orientation.is_none());
    }

    #[tokio::test]
    async fn grpc_actuator_sink_stub_logs() {
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();
        let sink = GrpcActuatorSink::new(channel, vec!["j1".into()], tokio::runtime::Handle::current());
        let frame = CommandFrame::zero(1);
        assert!(sink.send(&frame).is_ok());
        assert!(!sink.had_error());
    }

    #[tokio::test]
    async fn grpc_actuator_sink_from_control_manifest_preserves_canonical_metadata() {
        let mut control_manifest = ControlInterfaceManifest {
            version: 1,
            manifest_digest: String::new(),
            channels: vec![
                roz_core::embodiment::binding::ControlChannelDef {
                    name: "joint0/velocity".into(),
                    interface_type: roz_core::embodiment::binding::CommandInterfaceType::JointVelocity,
                    units: "rad/s".into(),
                    frame_id: "joint0_link".into(),
                },
                roz_core::embodiment::binding::ControlChannelDef {
                    name: "joint1/velocity".into(),
                    interface_type: roz_core::embodiment::binding::CommandInterfaceType::JointVelocity,
                    units: "rad/s".into(),
                    frame_id: "joint1_link".into(),
                },
            ],
            bindings: vec![
                roz_core::embodiment::binding::ChannelBinding {
                    physical_name: "joint0".into(),
                    channel_index: 0,
                    binding_type: roz_core::embodiment::binding::BindingType::JointVelocity,
                    frame_id: "joint0_link".into(),
                    units: "rad/s".into(),
                    semantic_role: None,
                },
                roz_core::embodiment::binding::ChannelBinding {
                    physical_name: "joint1".into(),
                    channel_index: 1,
                    binding_type: roz_core::embodiment::binding::BindingType::JointVelocity,
                    frame_id: "joint1_link".into(),
                    units: "rad/s".into(),
                    semantic_role: None,
                },
            ],
        };
        control_manifest.stamp_digest();
        let runtime = tokio::runtime::Handle::current();
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();

        let canonical =
            GrpcActuatorSink::from_control_manifest(channel, &control_manifest, "manipulator", runtime).unwrap();

        assert_eq!(
            canonical.channel_names,
            vec!["joint0_joint".to_string(), "joint1_joint".to_string()]
        );
        assert_eq!(canonical.robot_class, "manipulator");
        assert_eq!(canonical.command_mode, proto::JointCommandMode::JointVelocity as i32);
    }

    #[tokio::test]
    async fn grpc_actuator_sink_preserves_non_manipulator_physical_names() {
        let mut control_manifest = ControlInterfaceManifest {
            version: 1,
            manifest_digest: String::new(),
            channels: vec![roz_core::embodiment::binding::ControlChannelDef {
                name: "body/vx".into(),
                interface_type: roz_core::embodiment::binding::CommandInterfaceType::JointVelocity,
                units: "m/s".into(),
                frame_id: "base_link".into(),
            }],
            bindings: vec![roz_core::embodiment::binding::ChannelBinding {
                physical_name: "body/vx".into(),
                channel_index: 0,
                binding_type: roz_core::embodiment::binding::BindingType::Command,
                frame_id: "base_link".into(),
                units: "m/s".into(),
                semantic_role: None,
            }],
        };
        control_manifest.stamp_digest();
        let runtime = tokio::runtime::Handle::current();
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();

        let canonical = GrpcActuatorSink::from_control_manifest(channel, &control_manifest, "mobile", runtime).unwrap();

        assert_eq!(canonical.channel_names, vec!["body/vx".to_string()]);
        assert_eq!(canonical.robot_class, "mobile");
    }

    #[tokio::test]
    async fn grpc_actuator_sink_rejects_mixed_actuator_layouts() {
        let mut control_manifest = ControlInterfaceManifest {
            version: 1,
            manifest_digest: String::new(),
            channels: vec![
                roz_core::embodiment::binding::ControlChannelDef {
                    name: "joint0/velocity".into(),
                    interface_type: roz_core::embodiment::binding::CommandInterfaceType::JointVelocity,
                    units: "rad/s".into(),
                    frame_id: "joint0_link".into(),
                },
                roz_core::embodiment::binding::ControlChannelDef {
                    name: "joint1/position".into(),
                    interface_type: roz_core::embodiment::binding::CommandInterfaceType::JointPosition,
                    units: "rad".into(),
                    frame_id: "joint1_link".into(),
                },
            ],
            bindings: vec![
                roz_core::embodiment::binding::ChannelBinding {
                    physical_name: "joint0".into(),
                    channel_index: 0,
                    binding_type: roz_core::embodiment::binding::BindingType::JointVelocity,
                    frame_id: "joint0_link".into(),
                    units: "rad/s".into(),
                    semantic_role: None,
                },
                roz_core::embodiment::binding::ChannelBinding {
                    physical_name: "joint1".into(),
                    channel_index: 1,
                    binding_type: roz_core::embodiment::binding::BindingType::JointPosition,
                    frame_id: "joint1_link".into(),
                    units: "rad".into(),
                    semantic_role: None,
                },
            ],
        };
        control_manifest.stamp_digest();
        let runtime = tokio::runtime::Handle::current();
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();

        let error = match GrpcActuatorSink::from_control_manifest(channel, &control_manifest, "manipulator", runtime) {
            Ok(_) => panic!("mixed actuator layouts should be rejected"),
            Err(error) => error,
        };

        assert!(error.to_string().contains("homogeneous actuator interfaces"));
    }

    #[tokio::test]
    async fn grpc_actuator_sink_uses_ros_joint_names_for_ur5_manipulator_manifest() {
        let robot: roz_core::manifest::EmbodimentManifest =
            toml::from_str(include_str!("../../../examples/ur5/embodiment.toml")).expect("ur5 manifest");
        let control_manifest = robot.control_interface_manifest().expect("control manifest");
        let runtime = tokio::runtime::Handle::current();
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();

        let canonical =
            GrpcActuatorSink::from_control_manifest(channel, &control_manifest, "manipulator", runtime).unwrap();

        assert_eq!(
            canonical.channel_names,
            vec![
                "shoulder_pan_joint".to_string(),
                "shoulder_lift_joint".to_string(),
                "elbow_joint".to_string(),
                "wrist_1_joint".to_string(),
                "wrist_2_joint".to_string(),
                "wrist_3_joint".to_string(),
            ]
        );
    }

    #[tokio::test]
    async fn grpc_actuator_sink_clears_last_error_without_bailing() {
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();
        let sink = GrpcActuatorSink::new(channel, vec!["j1".into()], tokio::runtime::Handle::current());

        // Simulate a background error.
        sink.last_error.store(true, Ordering::Relaxed);

        // send() should warn but NOT bail — keeps 100Hz throughput.
        let result = sink.send(&CommandFrame::zero(1));
        assert!(result.is_ok(), "send should not bail on previous error");

        // Error flag should be cleared after surfacing.
        assert!(!sink.had_error());
    }

    #[tokio::test]
    async fn grpc_actuator_sink_rejects_frame_width_mismatch_before_rpc() {
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();
        let sink = GrpcActuatorSink::new(
            channel,
            vec!["j1".into(), "j2".into()],
            tokio::runtime::Handle::current(),
        );

        let error = sink.send(&CommandFrame::zero(1)).unwrap_err();

        assert!(error.to_string().contains("command frame width mismatch"));
        assert!(
            !sink.had_error(),
            "local validation should fail before any background RPC"
        );
    }

    #[tokio::test]
    async fn grpc_actuator_sink_drop_marks_owned_lease_for_release() {
        let channel = tonic::transport::Channel::from_static("http://127.0.0.1:9999").connect_lazy();
        let sink = GrpcActuatorSink::new(channel, vec!["j1".into()], tokio::runtime::Handle::current());
        let lease_state = Arc::clone(&sink.lease_state);
        *sink.lease_state.lock() = LeaseState::Owned;

        drop(sink);
        tokio::task::yield_now().await;

        assert_eq!(*lease_state.lock(), LeaseState::DropRequested);
    }

    #[tokio::test]
    #[ignore]
    async fn grpc_sensor_source_receives_poses() {
        let mut source = GrpcSensorSource::connect("http://127.0.0.1:9090").await.unwrap();

        // Give the background stream time to receive at least one batch.
        tokio::time::sleep(Duration::from_secs(1)).await;

        let frame = source.try_recv();
        assert!(frame.is_some(), "should receive sensor data from bridge");
        let frame = frame.unwrap();
        assert!(!frame.entities.is_empty(), "should have entities");
        println!("Received {} entities", frame.entities.len());
    }
}
